import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import swaggerUi from 'swagger-ui-express';
import { appointments, audit, auditLogs, claims, patients, providers, pool, Role, AppointmentStatus, ClaimStatus } from './db/store';
import { listAppointments, listAuditLogs, listClaims, listPatients, listProviders, insertAudit, databaseEnabled } from './db/repository';
import openapi from '../openapi.json';

const app = express(); app.use(cors()); app.use(express.json());
const secret = process.env.JWT_SECRET || 'demo-secret';
type User = { email:string; role:Role }; type Authed = Request & { user?:User };
const demoUsers:Record<string,{role:Role;password:string}> = {
  'admin@northstar.test': {role:'admin',password:'demo-password'},
  'scheduler@northstar.test': {role:'scheduler',password:'demo-password'},
  'billing@northstar.test': {role:'billing',password:'demo-password'},
  'demo@northstar.test': {role:'admin',password:'demo-password'}
};
const auth = (req:Authed,res:Response,next:NextFunction) => { const token=req.headers.authorization?.replace('Bearer ',''); if (!token) return res.status(401).json({message:'Authentication required'}); try { req.user=jwt.verify(token,secret) as User; next(); } catch { res.status(401).json({message:'Invalid token'}); } };
const role = (...allowed:Role[]) => (req:Authed,res:Response,next:NextFunction) => req.user && allowed.includes(req.user.role) ? next() : res.status(403).json({message:'Insufficient role'});
const page = <T>(items:T[], req:Request) => { const q=String(req.query.q||'').toLowerCase(); const pageNum=Math.max(1,Number(req.query.page||1)); const limit=Math.min(50,Math.max(1,Number(req.query.limit||10))); const filtered=q?items.filter(x=>JSON.stringify(x).toLowerCase().includes(q)):items; const sortBy=String(req.query.sortBy||''); const direction=req.query.order==='desc'?-1:1; const sorted=sortBy?[...filtered].sort((a,b)=>String((a as Record<string,unknown>)[sortBy]??'').localeCompare(String((b as Record<string,unknown>)[sortBy]??''))*direction):filtered; return {data:sorted.slice((pageNum-1)*limit,pageNum*limit),pagination:{page:pageNum,limit,total:sorted.length,totalPages:Math.ceil(sorted.length/limit),sortBy:sortBy||null,order:direction===1?'asc':'desc'}}; };

app.get('/health',(_,res)=>res.json({status:'ok',syntheticData:true}));
app.post('/api/auth/login',(req,res)=>{ const email=String(req.body.email||'').toLowerCase(); const account=demoUsers[email]; if(!account||req.body.password!==account.password) return res.status(401).json({message:'Invalid demo credentials'}); const requestedRole=req.body.role as Role|undefined; if(requestedRole&&requestedRole!==account.role) return res.status(403).json({message:'Role does not match this demo account'}); const user={email,role:account.role}; res.json({token:jwt.sign(user,secret,{expiresIn:'8h'}),user}); });
app.get('/api/providers',auth,async(req,res)=>{ const records=databaseEnabled?await listProviders(String(req.query.q||'')):providers; res.json(page(records||[],req)); });
app.get('/api/patients',auth,async(req,res)=>{ const records=databaseEnabled?await listPatients(String(req.query.q||'')):patients; res.json(page(records||[],req)); });
app.post('/api/providers',auth,role('admin'),async(req:Authed,res)=>{ const {name,specialty,location}=req.body; if(!name||!specialty||!location) return res.status(400).json({message:'name, specialty, and location are required'}); const item={id:`pr-${Date.now()}`,name,specialty,location,active:true}; if(pool) await pool.query('INSERT INTO providers (id,name,specialty,location,active) VALUES ($1,$2,$3,$4,$5)',[item.id,item.name,item.specialty,item.location,item.active]); else providers.push(item); audit(req.user!.email,'created','provider',item.id,{specialty}); await insertAudit(req.user!.email,'created','provider',item.id,{specialty}); res.status(201).json(item); });
app.post('/api/patients',auth,role('admin','scheduler'),async(req:Authed,res)=>{ const {displayName,birthYear,coverage}=req.body; if(!displayName||!birthYear||!coverage) return res.status(400).json({message:'displayName, birthYear, and coverage are required'}); const item={id:`pt-${Date.now()}`,displayName,birthYear,coverage}; if(pool) await pool.query('INSERT INTO patients (id,display_name,birth_year,coverage) VALUES ($1,$2,$3,$4)',[item.id,item.displayName,item.birthYear,item.coverage]); else patients.push(item); audit(req.user!.email,'created','patient',item.id,{coverage}); await insertAudit(req.user!.email,'created','patient',item.id,{coverage}); res.status(201).json(item); });
app.get('/api/appointments',auth,async(req,res)=>{ let data=databaseEnabled?(await listAppointments(req.query.status as string|undefined,req.query.providerId as string|undefined))||[]:appointments; if(!databaseEnabled){ if(req.query.status) data=data.filter(a=>a.status===req.query.status); if(req.query.providerId) data=data.filter(a=>a.providerId===req.query.providerId); data=[...data].sort((a,b)=>String(a.startsAt).localeCompare(String(b.startsAt))); } res.json(page(data,req)); });
app.post('/api/appointments',auth,role('admin','scheduler'),async(req:Authed,res)=>{ const {providerId,patientId,startsAt,endsAt,reason}=req.body; if(!providerId||!patientId||!startsAt||!endsAt||!reason) return res.status(400).json({message:'providerId, patientId, startsAt, endsAt, reason are required'}); if(pool){ const conflict=await pool.query("SELECT id FROM appointments WHERE provider_id=$1 AND status<>'cancelled' AND starts_at < $3 AND ends_at > $2 LIMIT 1",[providerId,startsAt,endsAt]); if(conflict.rowCount) return res.status(409).json({message:'Provider already has an appointment in this time window'}); } else { const conflict=appointments.some(a=>a.providerId===providerId&&a.status!=='cancelled'&&new Date(startsAt)<new Date(a.endsAt)&&new Date(endsAt)>new Date(a.startsAt)); if(conflict) return res.status(409).json({message:'Provider already has an appointment in this time window'}); } const item={id:`apt-${Date.now()}`,providerId,patientId,startsAt,endsAt,status:'scheduled' as AppointmentStatus,reason,createdBy:req.user!.email}; if(pool) await pool.query('INSERT INTO appointments (id,provider_id,patient_id,starts_at,ends_at,status,reason,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)',[item.id,item.providerId,item.patientId,item.startsAt,item.endsAt,item.status,item.reason,item.createdBy]); else appointments.push(item); audit(req.user!.email,'created','appointment',item.id,{providerId,patientId}); await insertAudit(req.user!.email,'created','appointment',item.id,{providerId,patientId}); res.status(201).json(item); });
app.patch('/api/appointments/:id/status',auth,role('admin','scheduler'),async(req:Authed,res)=>{ const id=String(req.params.id); if(pool){ const result=await pool.query('UPDATE appointments SET status=$1 WHERE id=$2 RETURNING *',[req.body.status,id]); if(!result.rowCount) return res.status(404).json({message:'Appointment not found'}); const item=result.rows[0]; audit(req.user!.email,'status_changed','appointment',id,{status:req.body.status}); await insertAudit(req.user!.email,'status_changed','appointment',id,{status:req.body.status}); return res.json(item); } const item=appointments.find(a=>a.id===id); if(!item) return res.status(404).json({message:'Appointment not found'}); item.status=req.body.status as AppointmentStatus; audit(req.user!.email,'status_changed','appointment',item.id,{status:item.status}); res.json(item); });
app.get('/api/claims',auth,async(req,res)=>{ let data=databaseEnabled?(await listClaims(req.query.status as string|undefined))||[]:claims; if(!databaseEnabled&&req.query.status) data=data.filter(c=>c.status===req.query.status); res.json(page(data,req)); });
app.post('/api/claims',auth,role('admin','billing'),async(req:Authed,res)=>{ const {patientId,providerId,appointmentId,amountCents}=req.body; if(!patientId||!providerId||!appointmentId||!amountCents) return res.status(400).json({message:'patientId, providerId, appointmentId, and amountCents are required'}); if(pool){ const duplicate=await pool.query('SELECT id FROM claims WHERE appointment_id=$1 LIMIT 1',[appointmentId]); if(duplicate.rowCount) return res.status(409).json({message:'A claim already exists for this appointment'}); } else if(claims.some(c=>c.appointmentId===appointmentId)) return res.status(409).json({message:'A claim already exists for this appointment'}); const now=new Date().toISOString(); const item={id:`cl-${Date.now()}`,patientId,providerId,appointmentId,amountCents:Number(amountCents),status:'submitted' as ClaimStatus,submittedAt:now,updatedAt:now}; if(pool) await pool.query('INSERT INTO claims (id,patient_id,provider_id,appointment_id,amount_cents,status,submitted_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$7)',[item.id,item.patientId,item.providerId,item.appointmentId,item.amountCents,item.status,now]); else claims.push(item); audit(req.user!.email,'created','claim',item.id,{appointmentId,amountCents}); await insertAudit(req.user!.email,'created','claim',item.id,{appointmentId,amountCents}); res.status(201).json(item); });
app.patch('/api/claims/:id/status',auth,role('admin','billing'),async(req:Authed,res)=>{ const id=String(req.params.id); if(pool){ const result=await pool.query('UPDATE claims SET status=$1,updated_at=NOW() WHERE id=$2 RETURNING *',[req.body.status,id]); if(!result.rowCount) return res.status(404).json({message:'Claim not found'}); audit(req.user!.email,'status_changed','claim',id,{status:req.body.status}); await insertAudit(req.user!.email,'status_changed','claim',id,{status:req.body.status}); return res.json(result.rows[0]); } const item=claims.find(c=>c.id===id); if(!item) return res.status(404).json({message:'Claim not found'}); item.status=req.body.status as ClaimStatus; item.updatedAt=new Date().toISOString(); audit(req.user!.email,'status_changed','claim',item.id,{status:item.status}); res.json(item); });
app.post('/api/clearinghouse/eligibility',auth,role('admin','billing','scheduler'),(req:Authed,res)=>{ const patient=patients.find(p=>p.id===req.body.patientId); if(!patient) return res.status(404).json({message:'Patient not found'}); audit(req.user!.email,'eligibility_checked','patient',patient.id,{adapter:'mock-clearinghouse'}); res.json({adapter:'mock-clearinghouse',patientId:patient.id,eligible:true,coverage:patient.coverage,checkedAt:new Date().toISOString()}); });
app.get('/api/audit-logs',auth,role('admin'),async(req,res)=>{ const data=databaseEnabled?(await listAuditLogs())||[]:auditLogs; res.json(page(data,req)); });
app.get('/docs',swaggerUi.serve,swaggerUi.setup(openapi));
app.use((err:Error,_req:Request,res:Response,_next:NextFunction)=>res.status(500).json({message:err.message}));
export default app;
